package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecOrganiz<M extends BaseRecOrganiz<M>> extends Model<M> implements IBean {

	public void setRecOrganizId(java.lang.Integer recOrganizId) {
		set("rec_organiz_id", recOrganizId);
	}

	public java.lang.Integer getRecOrganizId() {
		return get("rec_organiz_id");
	}

	public void setRecOrganizName(java.lang.String recOrganizName) {
		set("rec_organiz_name", recOrganizName);
	}

	public java.lang.String getRecOrganizName() {
		return get("rec_organiz_name");
	}

}
