package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMessage<M extends BaseUserMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(java.lang.Integer messageId) {
		set("message_id", messageId);
	}

	public java.lang.Integer getMessageId() {
		return get("message_id");
	}

	public void setMessageCon(java.lang.String messageCon) {
		set("message_con", messageCon);
	}

	public java.lang.String getMessageCon() {
		return get("message_con");
	}

	public void setReceiveId(java.lang.Integer receiveId) {
		set("receive_id", receiveId);
	}

	public java.lang.Integer getReceiveId() {
		return get("receive_id");
	}

	public void setIsread(java.lang.String isread) {
		set("isread", isread);
	}

	public java.lang.String getIsread() {
		return get("isread");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

}
