package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuperviseRequire<M extends BaseSuperviseRequire<M>> extends Model<M> implements IBean {

	public void setDbrequireId(java.lang.Integer dbrequireId) {
		set("dbrequire_id", dbrequireId);
	}

	public java.lang.Integer getDbrequireId() {
		return get("dbrequire_id");
	}

	public void setRequireOrganizId(java.lang.String requireOrganizId) {
		set("require_organiz_id", requireOrganizId);
	}

	public java.lang.String getRequireOrganizId() {
		return get("require_organiz_id");
	}

	public void setRequireFinishLimit(java.lang.String requireFinishLimit) {
		set("require_finish_limit", requireFinishLimit);
	}

	public java.lang.String getRequireFinishLimit() {
		return get("require_finish_limit");
	}

	public void setSuperviseInfoId(java.lang.Integer superviseInfoId) {
		set("supervise_info_id", superviseInfoId);
	}

	public java.lang.Integer getSuperviseInfoId() {
		return get("supervise_info_id");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserOrganizId(java.lang.Integer cuserOrganizId) {
		set("cuser_organiz_id", cuserOrganizId);
	}

	public java.lang.Integer getCuserOrganizId() {
		return get("cuser_organiz_id");
	}

	public void setCuserOrganizName(java.lang.String cuserOrganizName) {
		set("cuser_organiz_name", cuserOrganizName);
	}

	public java.lang.String getCuserOrganizName() {
		return get("cuser_organiz_name");
	}

}
