package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeaderSchedule<M extends BaseLeaderSchedule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setSchPosition(java.lang.String schPosition) {
		set("sch_position", schPosition);
	}

	public java.lang.String getSchPosition() {
		return get("sch_position");
	}

	public void setLeaderid(java.lang.Integer leaderid) {
		set("leaderid", leaderid);
	}

	public java.lang.Integer getLeaderid() {
		return get("leaderid");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setStart(java.util.Date start) {
		set("start", start);
	}

	public java.util.Date getStart() {
		return get("start");
	}

	public void setEnd(java.util.Date end) {
		set("end", end);
	}

	public java.util.Date getEnd() {
		return get("end");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setSjType(java.lang.String sjType) {
		set("sj_type", sjType);
	}

	public java.lang.String getSjType() {
		return get("sj_type");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

}
