package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeaderInfo<M extends BaseLeaderInfo<M>> extends Model<M> implements IBean {

	public void setLeaderid(java.lang.Integer leaderid) {
		set("leaderid", leaderid);
	}

	public java.lang.Integer getLeaderid() {
		return get("leaderid");
	}

	public void setLeaderName(java.lang.String leaderName) {
		set("leader_name", leaderName);
	}

	public java.lang.String getLeaderName() {
		return get("leader_name");
	}

	public void setLeaderPosition(java.lang.String leaderPosition) {
		set("leader_position", leaderPosition);
	}

	public java.lang.String getLeaderPosition() {
		return get("leader_position");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

	public void setLeaderAge(java.lang.String leaderAge) {
		set("leader_age", leaderAge);
	}

	public java.lang.String getLeaderAge() {
		return get("leader_age");
	}

	public void setLeaderSex(java.lang.String leaderSex) {
		set("leader_sex", leaderSex);
	}

	public java.lang.String getLeaderSex() {
		return get("leader_sex");
	}

}
