package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecpApply<M extends BaseRecpApply<M>> extends Model<M> implements IBean {

	public void setApplyId(java.lang.Integer applyId) {
		set("apply_id", applyId);
	}

	public java.lang.Integer getApplyId() {
		return get("apply_id");
	}

	public void setPersionName(java.lang.String persionName) {
		set("persion_name", persionName);
	}

	public java.lang.String getPersionName() {
		return get("persion_name");
	}

	public void setPersionPosition(java.lang.String persionPosition) {
		set("persion_position", persionPosition);
	}

	public java.lang.String getPersionPosition() {
		return get("persion_position");
	}

	public void setPersionDepart(java.lang.String persionDepart) {
		set("persion_depart", persionDepart);
	}

	public java.lang.String getPersionDepart() {
		return get("persion_depart");
	}

	public void setPersionPurposeTolz(java.lang.String persionPurposeTolz) {
		set("persion_purpose_tolz", persionPurposeTolz);
	}

	public java.lang.String getPersionPurposeTolz() {
		return get("persion_purpose_tolz");
	}

	public void setPersionStartTime(java.util.Date persionStartTime) {
		set("persion_start_time", persionStartTime);
	}

	public java.util.Date getPersionStartTime() {
		return get("persion_start_time");
	}

	public void setPersionEndTime(java.util.Date persionEndTime) {
		set("persion_end_time", persionEndTime);
	}

	public java.util.Date getPersionEndTime() {
		return get("persion_end_time");
	}

	public void setPersionEndTimeTrue(java.util.Date persionEndTimeTrue) {
		set("persion_end_time_true", persionEndTimeTrue);
	}

	public java.util.Date getPersionEndTimeTrue() {
		return get("persion_end_time_true");
	}

	public void setRecpFlag(java.lang.String recpFlag) {
		set("recp_flag", recpFlag);
	}

	public java.lang.String getRecpFlag() {
		return get("recp_flag");
	}

	public void setApprovalFlag(java.lang.String approvalFlag) {
		set("approval_flag", approvalFlag);
	}

	public java.lang.String getApprovalFlag() {
		return get("approval_flag");
	}

	public void setApprovalCon(java.lang.String approvalCon) {
		set("approval_con", approvalCon);
	}

	public java.lang.String getApprovalCon() {
		return get("approval_con");
	}

	public void setFinishFlag(java.lang.String finishFlag) {
		set("finish_flag", finishFlag);
	}

	public java.lang.String getFinishFlag() {
		return get("finish_flag");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserOrganizId(java.lang.Integer cuserOrganizId) {
		set("cuser_organiz_id", cuserOrganizId);
	}

	public java.lang.Integer getCuserOrganizId() {
		return get("cuser_organiz_id");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

}
