package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsApp<M extends BaseNewsApp<M>> extends Model<M> implements IBean {

	public void setAppId(java.lang.Integer appId) {
		set("app_id", appId);
	}

	public java.lang.Integer getAppId() {
		return get("app_id");
	}

	public void setAppTitle(java.lang.String appTitle) {
		set("app_title", appTitle);
	}

	public java.lang.String getAppTitle() {
		return get("app_title");
	}

	public void setAppType(java.lang.String appType) {
		set("app_type", appType);
	}

	public java.lang.String getAppType() {
		return get("app_type");
	}

	public void setAppUrls(java.lang.String appUrls) {
		set("app_urls", appUrls);
	}

	public java.lang.String getAppUrls() {
		return get("app_urls");
	}

	public void setAppFiles(java.lang.String appFiles) {
		set("app_files", appFiles);
	}

	public java.lang.String getAppFiles() {
		return get("app_files");
	}

	public void setAppContent(java.lang.String appContent) {
		set("app_content", appContent);
	}

	public java.lang.String getAppContent() {
		return get("app_content");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserOrganizName(java.lang.String cuserOrganizName) {
		set("cuser_organiz_name", cuserOrganizName);
	}

	public java.lang.String getCuserOrganizName() {
		return get("cuser_organiz_name");
	}

	public void setCuserOrganizId(java.lang.Integer cuserOrganizId) {
		set("cuser_organiz_id", cuserOrganizId);
	}

	public java.lang.Integer getCuserOrganizId() {
		return get("cuser_organiz_id");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

}
