package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuperviseProgressInfo<M extends BaseSuperviseProgressInfo<M>> extends Model<M> implements IBean {

	public void setProgressInfoId(java.lang.Integer progressInfoId) {
		set("progress_info_id", progressInfoId);
	}

	public java.lang.Integer getProgressInfoId() {
		return get("progress_info_id");
	}

	public void setSuperviseProgressId(java.lang.Integer superviseProgressId) {
		set("supervise_progress_id", superviseProgressId);
	}

	public java.lang.Integer getSuperviseProgressId() {
		return get("supervise_progress_id");
	}

	public void setProgressInfoCon(java.lang.String progressInfoCon) {
		set("progress_info_con", progressInfoCon);
	}

	public java.lang.String getProgressInfoCon() {
		return get("progress_info_con");
	}

	public void setProgressInfoStatus(java.lang.String progressInfoStatus) {
		set("progress_info_status", progressInfoStatus);
	}

	public java.lang.String getProgressInfoStatus() {
		return get("progress_info_status");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

	public void setCuserOrganizId(java.lang.Integer cuserOrganizId) {
		set("cuser_organiz_id", cuserOrganizId);
	}

	public java.lang.Integer getCuserOrganizId() {
		return get("cuser_organiz_id");
	}

	public void setCuserOrganizName(java.lang.String cuserOrganizName) {
		set("cuser_organiz_name", cuserOrganizName);
	}

	public java.lang.String getCuserOrganizName() {
		return get("cuser_organiz_name");
	}

}
