package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRoleMenu<M extends BaseUserRoleMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserRoleId(java.lang.Integer userRoleId) {
		set("user_role_id", userRoleId);
	}

	public java.lang.Integer getUserRoleId() {
		return get("user_role_id");
	}

	public void setUserMenuId(java.lang.Integer userMenuId) {
		set("user_menu_id", userMenuId);
	}

	public java.lang.Integer getUserMenuId() {
		return get("user_menu_id");
	}

	public void setUserMenuUrl(java.lang.String userMenuUrl) {
		set("user_menu_url", userMenuUrl);
	}

	public java.lang.String getUserMenuUrl() {
		return get("user_menu_url");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

}
