package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuperviseProgressInfoApply<M extends BaseSuperviseProgressInfoApply<M>> extends Model<M> implements IBean {

	public void setProgressInfoApplyId(java.lang.Integer progressInfoApplyId) {
		set("progress_info_apply_id", progressInfoApplyId);
	}

	public java.lang.Integer getProgressInfoApplyId() {
		return get("progress_info_apply_id");
	}

	public void setProgressInfoId(java.lang.Integer progressInfoId) {
		set("progress_info_id", progressInfoId);
	}

	public java.lang.Integer getProgressInfoId() {
		return get("progress_info_id");
	}

	public void setApplyStatus(java.lang.String applyStatus) {
		set("apply_status", applyStatus);
	}

	public java.lang.String getApplyStatus() {
		return get("apply_status");
	}

	public void setApplyDate(java.util.Date applyDate) {
		set("apply_date", applyDate);
	}

	public java.util.Date getApplyDate() {
		return get("apply_date");
	}

	public void setApplyUserId(java.lang.Integer applyUserId) {
		set("apply_user_id", applyUserId);
	}

	public java.lang.Integer getApplyUserId() {
		return get("apply_user_id");
	}

	public void setApplyUserName(java.lang.String applyUserName) {
		set("apply_user_name", applyUserName);
	}

	public java.lang.String getApplyUserName() {
		return get("apply_user_name");
	}

	public void setApplyUserOrganizId(java.lang.Integer applyUserOrganizId) {
		set("apply_user_organiz_id", applyUserOrganizId);
	}

	public java.lang.Integer getApplyUserOrganizId() {
		return get("apply_user_organiz_id");
	}

	public void setApplyUserOrganizName(java.lang.String applyUserOrganizName) {
		set("apply_user_organiz_name", applyUserOrganizName);
	}

	public java.lang.String getApplyUserOrganizName() {
		return get("apply_user_organiz_name");
	}

}
