package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuperviseInfo<M extends BaseSuperviseInfo<M>> extends Model<M> implements IBean {

	public void setInfoId(java.lang.Integer infoId) {
		set("info_id", infoId);
	}

	public java.lang.Integer getInfoId() {
		return get("info_id");
	}

	public void setInfoType(java.lang.String infoType) {
		set("info_type", infoType);
	}

	public java.lang.String getInfoType() {
		return get("info_type");
	}

	public void setInfoTitle(java.lang.String infoTitle) {
		set("info_title", infoTitle);
	}

	public java.lang.String getInfoTitle() {
		return get("info_title");
	}

	public void setInfoCon(java.lang.String infoCon) {
		set("info_con", infoCon);
	}

	public java.lang.String getInfoCon() {
		return get("info_con");
	}

	public void setInfoSno(java.lang.String infoSno) {
		set("info_sno", infoSno);
	}

	public java.lang.String getInfoSno() {
		return get("info_sno");
	}

	public void setInfoImgUrl(java.lang.String infoImgUrl) {
		set("info_img_url", infoImgUrl);
	}

	public java.lang.String getInfoImgUrl() {
		return get("info_img_url");
	}

	public void setRecSno(java.lang.String recSno) {
		set("rec_sno", recSno);
	}

	public java.lang.String getRecSno() {
		return get("rec_sno");
	}

	public void setRecOrganizId(java.lang.String recOrganizId) {
		set("rec_organiz_id", recOrganizId);
	}

	public java.lang.String getRecOrganizId() {
		return get("rec_organiz_id");
	}

	public void setInfoApprovalType(java.lang.String infoApprovalType) {
		set("info_approval_type", infoApprovalType);
	}

	public java.lang.String getInfoApprovalType() {
		return get("info_approval_type");
	}

	public void setRecTime(java.util.Date recTime) {
		set("rec_time", recTime);
	}

	public java.util.Date getRecTime() {
		return get("rec_time");
	}

	public void setIsfinish(java.lang.String isfinish) {
		set("isfinish", isfinish);
	}

	public java.lang.String getIsfinish() {
		return get("isfinish");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

	public void setCuserOrganizId(java.lang.Integer cuserOrganizId) {
		set("cuser_organiz_id", cuserOrganizId);
	}

	public java.lang.Integer getCuserOrganizId() {
		return get("cuser_organiz_id");
	}

	public void setCuserOrganizName(java.lang.String cuserOrganizName) {
		set("cuser_organiz_name", cuserOrganizName);
	}

	public java.lang.String getCuserOrganizName() {
		return get("cuser_organiz_name");
	}

	public void setIsdelete(java.lang.String isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.String getIsdelete() {
		return get("isdelete");
	}

}
