package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoomSchedule<M extends BaseRoomSchedule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setAppReason(java.lang.String appReason) {
		set("app_reason", appReason);
	}

	public java.lang.String getAppReason() {
		return get("app_reason");
	}

	public void setRoomNumber(java.lang.Integer roomNumber) {
		set("room_number", roomNumber);
	}

	public java.lang.Integer getRoomNumber() {
		return get("room_number");
	}

	public void setRoomid(java.lang.Integer roomid) {
		set("roomid", roomid);
	}

	public java.lang.Integer getRoomid() {
		return get("roomid");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setStart(java.util.Date start) {
		set("start", start);
	}

	public java.util.Date getStart() {
		return get("start");
	}

	public void setEnd(java.util.Date end) {
		set("end", end);
	}

	public java.util.Date getEnd() {
		return get("end");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCheckUserid(java.lang.Integer checkUserid) {
		set("check_userid", checkUserid);
	}

	public java.lang.Integer getCheckUserid() {
		return get("check_userid");
	}

	public void setApplyDate(java.util.Date applyDate) {
		set("apply_date", applyDate);
	}

	public java.util.Date getApplyDate() {
		return get("apply_date");
	}

	public void setRoomShStatus(java.lang.String roomShStatus) {
		set("room_sh_status", roomShStatus);
	}

	public java.lang.String getRoomShStatus() {
		return get("room_sh_status");
	}

	public void setRoomIdea(java.lang.String roomIdea) {
		set("room_idea", roomIdea);
	}

	public java.lang.String getRoomIdea() {
		return get("room_idea");
	}

}
