package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecpFeed<M extends BaseRecpFeed<M>> extends Model<M> implements IBean {

	public void setFeedId(java.lang.Integer feedId) {
		set("feed_id", feedId);
	}

	public java.lang.Integer getFeedId() {
		return get("feed_id");
	}

	public void setRequireId(java.lang.Integer requireId) {
		set("require_id", requireId);
	}

	public java.lang.Integer getRequireId() {
		return get("require_id");
	}

	public void setFeedCon(java.lang.String feedCon) {
		set("feed_con", feedCon);
	}

	public java.lang.String getFeedCon() {
		return get("feed_con");
	}

	public void setFeedOrganiz(java.lang.String feedOrganiz) {
		set("feed_organiz", feedOrganiz);
	}

	public java.lang.String getFeedOrganiz() {
		return get("feed_organiz");
	}

	public void setFeedStatus(java.lang.String feedStatus) {
		set("feed_status", feedStatus);
	}

	public java.lang.String getFeedStatus() {
		return get("feed_status");
	}

	public void setFeedIdea(java.lang.String feedIdea) {
		set("feed_idea", feedIdea);
	}

	public java.lang.String getFeedIdea() {
		return get("feed_idea");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCuserId(java.lang.Integer cuserId) {
		set("cuser_id", cuserId);
	}

	public java.lang.Integer getCuserId() {
		return get("cuser_id");
	}

	public void setCuserName(java.lang.String cuserName) {
		set("cuser_name", cuserName);
	}

	public java.lang.String getCuserName() {
		return get("cuser_name");
	}

}
