package com.sysoa.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuperviseProgress<M extends BaseSuperviseProgress<M>> extends Model<M> implements IBean {

	public void setProgressId(java.lang.Integer progressId) {
		set("progress_id", progressId);
	}

	public java.lang.Integer getProgressId() {
		return get("progress_id");
	}

	public void setProgressStatus(java.lang.String progressStatus) {
		set("progress_status", progressStatus);
	}

	public java.lang.String getProgressStatus() {
		return get("progress_status");
	}

	public void setSuperviseInfoId(java.lang.Integer superviseInfoId) {
		set("supervise_info_id", superviseInfoId);
	}

	public java.lang.Integer getSuperviseInfoId() {
		return get("supervise_info_id");
	}

	public void setUdate(java.util.Date udate) {
		set("udate", udate);
	}

	public java.util.Date getUdate() {
		return get("udate");
	}

	public void setUuserId(java.lang.Integer uuserId) {
		set("uuser_id", uuserId);
	}

	public java.lang.Integer getUuserId() {
		return get("uuser_id");
	}

	public void setUuserName(java.lang.String uuserName) {
		set("uuser_name", uuserName);
	}

	public java.lang.String getUuserName() {
		return get("uuser_name");
	}

	public void setUuserOrganizName(java.lang.String uuserOrganizName) {
		set("uuser_organiz_name", uuserOrganizName);
	}

	public java.lang.String getUuserOrganizName() {
		return get("uuser_organiz_name");
	}

	public void setUuserOrganizId(java.lang.Integer uuserOrganizId) {
		set("uuser_organiz_id", uuserOrganizId);
	}

	public java.lang.Integer getUuserOrganizId() {
		return get("uuser_organiz_id");
	}

}
