package com.sysoa.integrate.model;

import com.sysoa.model.base.BaseIntegratedApproval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegratedApproval extends BaseIntegratedApproval<IntegratedApproval> {
	public static final IntegratedApproval dao = new IntegratedApproval();
}
