package com.sysoa.integrate.model;

import java.util.List;

import com.sysoa.model.base.BaseIntegratedHandling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegratedHandling extends BaseIntegratedHandling<IntegratedHandling> {
	public static final IntegratedHandling dao = new IntegratedHandling();
	
	
	public List<IntegratedHandling> findbyinfoid(Integer infoid){
		
		return dao.find("select * from t_integrated_handling where integrated_info_id= ? ",infoid);
	}
}
