package com.sysoa.model.data;

import com.sysoa.model.base.BaseIntegratedHandling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegratedHandling extends BaseIntegratedHandling<IntegratedHandling> {
	public static final IntegratedHandling dao = new IntegratedHandling();
}
