package com.sysoa.model.data;

import com.sysoa.model.base.BaseIntegratedInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegratedInfo extends BaseIntegratedInfo<IntegratedInfo> {
	public static final IntegratedInfo dao = new IntegratedInfo();
}
