package com.sysoa.model.data;

import com.sysoa.model.base.BaseLeaderSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaderSchedule extends BaseLeaderSchedule<LeaderSchedule> {
	public static final LeaderSchedule dao = new LeaderSchedule();
}
