package com.sysoa.model.data;

import com.sysoa.model.base.BaseLeaderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaderInfo extends BaseLeaderInfo<LeaderInfo> {
	public static final LeaderInfo dao = new LeaderInfo();
}
