package com.sysoa.model.data;

import com.sysoa.model.base.BaseNewsApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsApp extends BaseNewsApp<NewsApp> {
	public static final NewsApp dao = new NewsApp();
}
