package com.sysoa.model.data;

import com.sysoa.model.base.BaseNewsApproval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsApproval extends BaseNewsApproval<NewsApproval> {
	public static final NewsApproval dao = new NewsApproval();
}
