package com.sysoa.model.data;

import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.sysoa.model.base.BaseRecOrganiz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecOrganiz extends BaseRecOrganiz<RecOrganiz> {
	public static final RecOrganiz dao = new RecOrganiz();
	
	
	
	/**
	 * find all
	 * @return
	 */
	public List<RecOrganiz> findAll(){
		return findAll(null);
	}
	
	/**
	 * find all by order
	 * @param order
	 * @return
	 */
	public List<RecOrganiz> findAll(String order){
		StringBuilder sb = new StringBuilder("select * from t_rec_organiz ");
		if(StringUtils.isEmpty(order)){
			return dao.find(sb.append("order by id desc").toString());
		}else{
			return dao.find(sb.append(order).toString());
		}
	}
}
