package com.sysoa.model.data;

import com.sysoa.model.base.BaseRecpApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecpApply extends BaseRecpApply<RecpApply> {
	public static final RecpApply dao = new RecpApply();
}
