package com.sysoa.model.data;

import com.sysoa.model.base.BaseRecpRequire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecpRequire extends BaseRecpRequire<RecpRequire> {
	public static final RecpRequire dao = new RecpRequire();
}
