package com.sysoa.model.data;

import com.sysoa.model.base.BaseRecpFeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecpFeed extends BaseRecpFeed<RecpFeed> {
	public static final RecpFeed dao = new RecpFeed();
}
