package com.sysoa.model.data;

import com.sysoa.model.base.BaseRoomSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomSchedule extends BaseRoomSchedule<RoomSchedule> {
	public static final RoomSchedule dao = new RoomSchedule();
}
