package com.sysoa.model.data;

import com.sysoa.model.base.BaseSuperviseProgressInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseProgressInfo extends BaseSuperviseProgressInfo<SuperviseProgressInfo> {
	public static final SuperviseProgressInfo dao = new SuperviseProgressInfo();
	
}
