package com.sysoa.model.data;

import com.sysoa.model.base.BaseSuperviseRequire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseRequire extends BaseSuperviseRequire<SuperviseRequire> {
	public static final SuperviseRequire dao = new SuperviseRequire();
}
