package com.sysoa.model.data;

import com.sysoa.model.base.BaseSuperviseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseInfo extends BaseSuperviseInfo<SuperviseInfo> {
	public static final SuperviseInfo dao = new SuperviseInfo();
}
