package com.sysoa.model.data;

import com.sysoa.model.base.BaseSuperviseProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseProgress extends BaseSuperviseProgress<SuperviseProgress> {
	public static final SuperviseProgress dao = new SuperviseProgress();
}
