package com.sysoa.model.data;

import com.sysoa.model.base.BaseSuperviseProgressInfoApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseProgressInfoApply extends BaseSuperviseProgressInfoApply<SuperviseProgressInfoApply> {
	public static final SuperviseProgressInfoApply dao = new SuperviseProgressInfoApply();
}
