package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserEmployer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserEmployer extends BaseUserEmployer<UserEmployer> {
	public static final UserEmployer dao = new UserEmployer();
}
