package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserOrganiz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOrganiz extends BaseUserOrganiz<UserOrganiz> {
	public static final UserOrganiz dao = new UserOrganiz();
}
