package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserOrganizUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOrganizUser extends BaseUserOrganizUser<UserOrganizUser> {
	public static final UserOrganizUser dao = new UserOrganizUser();
}
