package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMenu extends BaseUserMenu<UserMenu> {
	public static final UserMenu dao = new UserMenu();
}
