package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoleMenu extends BaseUserRoleMenu<UserRoleMenu> {
	public static final UserRoleMenu dao = new UserRoleMenu();
}
