package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserOrganizEmployer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOrganizEmployer extends BaseUserOrganizEmployer<UserOrganizEmployer> {
	public static final UserOrganizEmployer dao = new UserOrganizEmployer();
}
