package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoleUser extends BaseUserRoleUser<UserRoleUser> {
	public static final UserRoleUser dao = new UserRoleUser();
}
