package com.sysoa.model.data;

import com.sysoa.model.base.BaseUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMessage extends BaseUserMessage<UserMessage> {
	public static final UserMessage dao = new UserMessage();
}
