package com.sysoa.supervise.model;

import com.sysoa.model.base.BaseSuperviseProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseProgress extends BaseSuperviseProgress<SuperviseProgress> {
	public static final SuperviseProgress dao = new SuperviseProgress();
	
	public SuperviseProgress querybyinfoid(Integer infoid){
		
		return dao.find("SELECT * FROM t_supervise_progress WHERE supervise_info_id = ? ", infoid).get(0);
	}
}
