package com.sysoa.supervise.model;

import java.util.List;
import java.util.Map;


import com.jfinal.plugin.activerecord.Page;
import com.sysoa.model.base.BaseSuperviseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseInfo extends BaseSuperviseInfo<SuperviseInfo> {
	public static final SuperviseInfo dao = new SuperviseInfo();
	
	/**
	 * 	根据创建人的部门id查询
	 * @return
	 */
	public Page<SuperviseInfo> queryBy1Organizid(Integer pageNumber, Integer pageSize, Integer organizid){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit , tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsf.isfinish = 1 AND tsr.cuser_organiz_id = ? "
				+ " ORDER BY tsf.cdate desc, tsr.require_finish_limit";		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect, organizid);
	}
	/**
	 * 	根据办理部门查
	 * @return
	 */
	public Page<SuperviseInfo> queryBy2Organizid(Integer pageNumber, Integer pageSize, Integer organizid){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit , tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsf.isfinish = 1 AND tsr.require_organiz_id like ? "
				+ " ORDER BY tsf.cdate desc, tsr.require_finish_limit ";		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect, "%"+organizid+",%");
	}
	/**
	 * 	根据督办事件的id
	 * @return
	 */
	public SuperviseInfo queryByINFOid(Integer id){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit ,"
				+ " tsr.dbrequire_id ,"
				+ " tuo.user_organiz_name, "
				+ " tsr.require_organiz_id ";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				+ " LEFT JOIN t_user_organiz tuo ON tuo.id=tsf.rec_organiz_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsf.info_id = ? "
				+ " ORDER BY tsf.cdate desc, tsr.require_finish_limit ";		
		
		return dao.find( select+sqlExceptSelect, id).get(0);
	}

	/**
	 * 查询已完成的督办工作
	 * @return
	 */
	public  Page<SuperviseInfo> querybycondition(Integer pageNumber, Integer pageSize, Map<String, Object> conditions){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit, tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsf.isfinish = 2";
		
		sqlExceptSelect += conditions.get("end") != null   ? " AND tsr.cdate< '"+conditions.get("end")+"'": " ";
		
		sqlExceptSelect += conditions.get("start") !=null  ? " AND tsr.cdate> '"+conditions.get("start")+"'" : " "; 
				
		sqlExceptSelect	+= " ORDER BY tsf.cdate desc, tsr.require_finish_limit";		
		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
	/**
	 * 查询所有的督办工作
	 * @return
	 */
	public  Page<SuperviseInfo> querybyall(Integer pageNumber, Integer pageSize){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit , tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' ";
				
		sqlExceptSelect	+= " ORDER BY tsf.cdate desc, tsr.require_finish_limit";		
		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
	/**
	 * 根据收件时间查询肖批示的所有的督办工作
	 * @return
	 */
	public  Page<SuperviseInfo> querybyallcondition(Integer pageNumber, Integer pageSize, Map<String, Object> conditions){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit , tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsf.info_approval_type= 'LEADER_APPROVAL_TYPE_02' ";
		
		sqlExceptSelect += conditions.get("end") != null   ? " AND tsf.rec_time < '"+conditions.get("end")+"'": " ";
		
		sqlExceptSelect += conditions.get("start") !=null  ? " AND tsf.rec_time > '"+conditions.get("start")+"'" : " "; 
				
		sqlExceptSelect	+= " ORDER BY tsf.rec_time desc ";			
		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
	/**
	 * 查询当前用户所有的督办工作
	 * @return
	 */
	public  Page<SuperviseInfo> querybyall_user(Integer pageNumber, Integer pageSize, Integer oid){
		
		String select = "SELECT tsf.*, tsp.progress_id, "
				+ " tsp.progress_status, tsp.supervise_info_con, tsr.cdate AS r_cdate, "
				+ " tsr.cuser_organiz_name AS r_organiz_name, "
				+ " tsr.require_finish_limit , tsr.require_organiz_id";
				//+ " tuo.user_organiz_name AS require_oragniz_name ";
		
		String sqlExceptSelect = "FROM t_supervise_info tsf "
				+ " LEFT JOIN t_supervise_require tsr ON tsf.info_id = tsr.supervise_info_id "
				//+ " LEFT JOIN t_user_organiz tuo ON tsr.require_organiz_id = tuo.id "
				+ " LEFT JOIN t_supervise_progress tsp ON tsf.info_id = tsp.supervise_info_id "
				+ " WHERE tsf.isdelete ='0' AND tsr.require_organiz_id like ? ";
				
		sqlExceptSelect	+= " ORDER BY tsf.cdate desc, tsr.require_finish_limit";		
		
		
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect, "%"+oid+",%");
	}
	/**
	 * 查询未被 下发的督办工作
	 * @return
	 */
	public List<SuperviseInfo> find1All(){
		
		return dao.find("select * from t_supervise_info order by cdate ");
		
	}
	public List<SuperviseInfo> find2All(){
		
		return dao.find("select * from t_supervise_info where isfinish < 1 order by cdate ");
		
	}
}
