package com.sysoa.supervise.model;

import com.sysoa.model.base.BaseSuperviseRequire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuperviseRequire extends BaseSuperviseRequire<SuperviseRequire> {
	public static final SuperviseRequire dao = new SuperviseRequire();
	
	
	public SuperviseRequire findbyINFOid(Integer id){
		
		return dao.find("select * from t_supervise_require where supervise_info_id=? ",id).get(0);
	}
}
